---
driver: vagrant

platforms:
- name: xubuntu-14.04
  driver_config:
    box: vbox-xubuntu-trusty
    box_url: ../../../packer/output-vagrant/vbox-xubuntu-trusty.box
    customize:
      memory: 2048
      natdnshostresolver1: "on"
    gui: true
    require_chef_omnibus: false
  provisioner:
    cookbook_files_glob: <%= %w{ README.*
                                 metadata.rb
                                 VERSION
                                 attributes/**/*
                                 files/**/*
                                 libraries/**/*
                                 providers/**/*
                                 recipes/**/*
                                 resources/**/*
                                 templates/**/* }.join(",") %>

provisioner: chef_zero

kitchen:
  test_base_path: spec

suites:
- name: default
  run_list:
  - recipe[apt::default]
  - recipe[wergstation::default]
  attributes:
    wergstation:
      user:
        id: vagrant
        group: vagrant
        home: /home/vagrant
